Algoritmo "SENHA_FIXA"


Var
   senha: inteiro
   //senhaC : inteiro

Inicio
   escreva("Digite a senha: ")
   leia(senha)
   //repita
   //senhaC <- 2002
   //se senha <> senhaC entao
   //escreva("Senha Invalida! Tente novamente: ")
   //leia(senha)
   //fimse
   //ate senha = senhac
   enquanto senha <> 2002 faca
      escreva("Senha Invalida! Tente novamente: ")
      leia(senha)
   fimenquanto
   escreval("Acesso permitido!")
Fimalgoritmo